apiVersion: v2
appVersion: "1.0"
description: A Helm chart for probate-wa-post-deployment-ft-tests App
name: probate-wa-post-deployment-ft-tests
home: https://github.com/hmcts/probate-wa-post-deployment-ft-tests
version: 0.0.3
maintainers:
  - name: HMCTS Probate team
dependencies:
  - name: java
    version: 5.0.0
    repository: https://hmctsprod.azurecr.io/helm/v1/repo/
